services:
  # Kafka (KRaft mode)
  kafka:
    image: apache/kafka:3.7.1
    container_name: messaging_kafka
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
#    ports: # ! We don't need it unless we want to access Kafka from the outside
#      - "9092:9092"
    volumes:
      - messaging_vol_kafka:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Spring application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging_server
    ports:
      - "8081:8081"
    environment:
      # Override the application.properties for container networking
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  messaging_vol_kafka: